baseURL = 'http://pixlark.github.io/'
languageCode = 'en-us'
title = 'Brooke Tilley'
theme = 'PaperMod'

[params]
defaultTheme = 'light'
disableThemeToggle = true

[params.homeInfoParams]
Title = 'Hello 👋'
Content = '''
My name is Brooke, I'm a software developer from New York. I recently graduated with a degree in Computer Science from [Binghamton University](https://www.binghamton.edu/).

&nbsp;  

Before leaving in September 2022, I was a full-time employee at Tesla, doing embedded work alongside higher-level Haskell programming. I also interned there over the summer of 2021.

&nbsp;  

Some of my primary interests are: programming language design and implementation, game development, music performance and composition, and creative writing.
'''

[params.assets]
disableHLJS = true

[markup.highlight]
guessSyntax = false

[markup.goldmark.renderer]
unsafe = true # Allow raw html to be inserted from a markdown source
